name: Deploy To EC2

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Test1
        run: |
          ls
          pwd
          echo "Hello World"    

      - name: Github Repository 파일 불러오기
        uses: actions/checkout@v4 # Github Repository 파일 불러오기 위한 라이브러리

      - name: Install Node.js
        uses: actions/setup-node@v4 # Node.js 설치를 위한 라이브러리
        with:
          node-version: '20'

      - name: 의존성 설치
        run: npm ci

      - name: 환경 변수 설정
        run: |
          echo '${{ secrets.ENV }}' > .env

      - name: Test3
        run: |
          ls
          cat .env
          cat src/app.service.ts

      - name: 테스트 코드 실행
        run: npm run test

      - name: SSH로 EC2에 접속하기
        uses: appleboy/ssh-action@v1.0.3 # SSH로 EC2에 접속하기 위한 라이브러리
        env:
          ENV: ${{ secrets.ENV }} # 환경 변수
        with:
          host: ${{ secrets.EC2_HOST }} # EC2의 주소
          username: ${{ secrets.EC2_USERNAME }} # EC2 접속 username
          key: ${{ secrets.EC2_PRIVATE_KEY }} # EC2의 Key 파일의 내부 텍스트
          envs: ENV
          script_stop: true # 아래 script 중 실패하는 명령이 하나라도 있으면 실패로 처리
          script: |
            cd /home/ubuntu/instagram_server_cicd
            rm -rf .env
            git pull origin main
            echo "$ENV" > .env
            npm i
            npm run build
            pm2 kill
            pm2 start dist/main.js --name "backend-server"